version: '3'

services:
  ### Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:latest
    environment:
      POSTGRES_DB: db_inventory
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5431:5431"
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_orders
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306

  ### Postgres database for Products
  db-products:
    container_name: db-products
    image: postgres:latest
    environment:
      POSTGRES_DB: db_products
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: -p 5432

  ### Postgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:latest
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5433

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    ports:
      - "8181:8181"
    expose:
      - 8181
    command: [ "start-dev" ]
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADD: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: test
      DB_PASSWORD: test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
